version: '3.8'
services:
  app:
    build: .
    container_name: rewardsapi-container
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start
